version: '3'
services:
  asp-net-core:
    container_name: asp-net-core
    build:
      context: .
      dockerfile: .dockerfiles/asp-net.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: .dockerfiles/postgres.Dockerfile
    ports:
      - '5432:5432'
