version: '3'

#! localhost -> asp net core
#! db server -> localhost -> postgres
#! pass token secret to backend

services:
  asp-net-core:
    # token secret needs to send
    container_name: asp-net-core
    build:
      context: .
      dockerfile: .dockerfiles/asp-net.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - token_secret=${TOKEN_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: .dockerfiles/postgres.Dockerfile
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: customEbay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
